### ISSUE TITLE
Update to 2.5.0 and 1.1.0

### ISSUE THREAD

**Issue by albertzak** [drblue/meteor-fullcalendar-scheduler#1]
```
v2.5.0 - FullCalendar
v1.1.0 - FullCalendar Scheduler
```

Thanks! 🍪

**Comment by drblue** [comment]
Here you go mate.
https://github.com/drblue/meteor-fullcalendar-scheduler/commit/832537b87a6c715acf66338ded2a4bdf0cf8f835
