### ISSUE TITLE
Version 2.7.0?

### ISSUE THREAD

**Issue by puddicombe** [drblue/meteor-fullcalendar-scheduler#3]
Hi Johan,
I would be most obliged if you were to update this version to be using v2.7.0 of full calendar and scheduler.
Many thanks!
James

**Comment by drblue** [comment]
Hi! Sorry for the late reply! I no longer actively develop Meteor-apps but there are steps included in the README.md in the repo for easy updating, and then you can just submit it to Atmosphere yourself and never have to worry about me forgetting to update the package again :)

**Comment by puddicombe** [comment]
Hi Johan,

Thank you for getting back to me with that positive suggestion.  I shall do
just as you suggest!

Best wishes,
James

On 12 May 2016 at 11:09, Johan Nordström notifications@github.com wrote:

> Hi! Sorry for the late reply! I no longer actively develop Meteor-apps but
> there are steps included in the README.md in the repo for easy updating,
> and then you can just submit it to Atmosphere yourself and never have to
> worry about me forgetting to update the package again :)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/drblue/meteor-fullcalendar-scheduler/issues/3#issuecomment-218715165

## 

James Puddicombe
Director
M: 07787 556007
W: www.voodoo.co.uk http://www.voodoo.co.uk/?source=email

http://uk.linkedin.com/in/puddicombe/
http://www.voodoo.co.uk?source=email
